---
- name: DYNU_CLIENT | Install package curl
  opkg:
    name: curl
    state: present
     
- name: DYNU_CLIENT | Install package ca-certificates
  opkg:
    name: ca-certificates
    state: present

- name: DYNU_CLIENT | Copy crontab settings
  lineinfile:
    line: "*/2 * * * * /usr/local/bin/update-ip.sh >/dev/null 2>&1"
    path: /etc/crontabs/root

